### ISSUE TITLE
update clear_acis_status_bits to use new HISTORY module

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#175]
https://github.com/cxcsds/ciao-contrib/blob/fe1fe329ae4bc71da9f3e855a44dad5158c65f50/ciao-4.11/contrib/lib/python3.5/site-packages/ciao_contrib/cxcdm_wrapper.py#L633-L635

This is related to #174 .  We can use the new in CIAO 4.11 `history` module to generate standard history records w/o a parameter file.

**Comment by DougBurke** [comment]
Do we still need to clear the status bits? I forget why we added it.

**Comment by kglotfelty** [comment]
I think so.  The afterglow tools ignore events w bits set, so they need to be cleared before it is rerun.

We could just drop status column, but there are some bits not set by ciao tools (ie acis format events , only in pipes, uses evt0 files which users can’t get..not even via chaser)

**Comment by DougBurke** [comment]
So, acis_clear_status_bits, which is the primary driver for this routine, has no parameter file. Maybe what we should do is add an optional flag to `clear_acis_status_bits` with a default of False, and only if it is set write out the history record. This would avoid changing `chandra_repro`. A nicer API would be to make `toolname` be optional, defaulting to `None`, and only write out the fake history record if it is set. This would require changing `chandra_repro` so that it doesn't set the `toolname` argument.

**Comment by kglotfelty** [comment]
Agree, 2nd option, using  `toolname=None`,  would be cleaner since it's only used for the history records.  It's a small change to `chandra_repro` and shouldn't affect things like regression tests since HISTORY isn't diffed.

**Comment by DougBurke** [comment]
See #186
