### ISSUE TITLE
blank sky scripts / x-post from ciaodoc

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#21]
@nplee 

From

https://icxc.harvard.edu/pipe/ciaodoc/2016/0560.html

we should take a look at the blank sky scripts to check the results look good for subarray data.  [I don't know if there is an issue or not; just wanted to put this here as a place holder.]

**Comment by nplee** [comment]
Bad news is that for scaling by the particle background, the results will be incorrect for sub-array data; but I have a fix for that now, so yay.  

Similarly, if scaling by exposure time, the sub-array data will be incorrect, but on the plus side, in the released version of the script, it will fail to run when using sub-array data using this scaling method due to missing keywords for some reason I still don't understand, but the user won't be getting the incorrect result.

**Comment by DougBurke** [comment]
I think this can be closed now, can't it @nplee ?

**Comment by nplee** [comment]
@DougBurke: Yep!
