### ISSUE TITLE
dax fit plots match sherpa

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#311]
@DougBurke , based on sherpa plotting changes like https://github.com/sherpa/sherpa/pull/667 I'm guessing there's an implicit RFE to have the dax plots try to plot model over data ?

**Comment by DougBurke** [comment]
If you try with the chips backend then I think you'll see that 'plot_fit' has model over data - and 667 was an attempt to fix this with matplotlib (due to changes in mpl v2) - e.g. https://github.com/sherpa/sherpa/pull/667#issuecomment-540062240

Which is a long-handed way of saying "probably yes", but I haven't seen what the current dax plots look like, so can't say for sure.
