### ISSUE TITLE
dax handling "background" in image fit task

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#451]
From @anetasie 

Need to reword the dax "background" parameter in the 2d fitting task.  We don't actually fit background region (background region is ignored).  What we call background is just a 2nd additive model component we fit to the source region, eg gaus+const where the "const" is interpreted as background.

**Comment by kglotfelty** [comment]
image fit should also allow for 

- [ ] exposure map
- [ ] psf

**Comment by DougBurke** [comment]
Technically there's no reason we couldn't fit the background model to the background region, it would just require a little bit of plumbing (since we can't use the background support in Sherpa as that's PHA only).

Of course, you then get into choices - you might want to actually fit the full model to the background region in case the source model extends that far (or you include a PSF that might cause the "source" model to extend out far enough) - but I think this is outside the scope of DAX
