### ISSUE TITLE
Can we suggest an energy-band to handle contamination changes?

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#482]
One for @kglotfelty.

Given an observation, hence observation range (possibly just TSTART as long as we can ignore merged event files) can we come up with a suggested "soft-band" mid-point based on the contamination model? The idea would be to say "hey, perhaps use this rather than the CSC 's' band". 

Of course, this then leads to doing the same for n observatiions - do we want to come up with a single band definition (the question would be how to wait the infividual band mid-points), or group the observations into chunks each with a different band, or give up on that idea and make it up to the user.

**Comment by kglotfelty** [comment]
well, there's

https://cxc.cfa.harvard.edu/ciao/why/low_energy_mono.html#mean_energy

which of course was generated using whatever the then current version of the contam model, and using the same spectral model that was used to come up with the 0.92 value; figure 5 shows  the effect of varying the model parameters.

To calculate this "on the fly" you need and ARF+RMF, a spectral model, and your choice of metric (ie just because we use mean, maybe the max is more appropriate).  The code to generate those plots is in

/data/lenin2/Projects/Bands/soft_band_v_ao.ipynb

and there's additional info in

/data/lenin2/Projects/Bands/SoftBand.pdf

**Comment by DougBurke** [comment]
So, do we want to move this into `ciao-contrib` (it's not complex but might be nice to make available)?
