### ISSUE TITLE
one command specreduce for grating data

### ISSUE THREAD

**Issue by hamogu** [cxcsds/ciao-contrib#495]
In discussion with a new Post-Doc I was asked why we have a single command to extract spectra and build arf/rmf for imaging data, but not for grating data. I replied "well, chandra_repro will do that for you anyway", but it turns out he wanted to extract another source in the field. Since chandra_repro *does* all the extraction and arf/rmf generation for on-axis sources, we probably have most of the code to do so. One could simply pass in a RA, DEC into chandra_repro :-)
Or, maybe more in line with precedent, would be a script "tg_specextract" and then `chandra_repro` could internally call that script to avoid duplication.

(It is possible that we have a `tg_specextract` already and I just don't know about it. We have so many scripts that I'm loosing track of all of them and I'm wondering if we should have something in between the alphabetical list of ahelp pages and full-prose long-form threads. Maybe an opinionated list or a tree-diagram. I have in fact tried to come up with a scheme, but failed to produce anything useful.)

**Comment by kglotfelty** [comment]
Looking at this ... something in `chandra_repro` is probably most sensible (definitely the path of least coding).  There's a lot of logic dealing w/ hrc vs acis, and in CC mode bootstrapping `a_p_e` -> `tg_r_e` -> `a_p_e` -> `tg_r_e` and then reconnecting with the L2 thread (status|gti|grade filtering) before diverging again to extra spectra and make responses.

Right now users have two options in `chandra_repro`:
1. `recreate_tg_mask=no` uses the coordinates (physical x,y) from the `REGION` block in the `primary/*evt2.fits` file.  This is because when the data are run in SDP, the 0th order location is (or maybe at least historically has been) manually adjusted and generally is expected to be the _best_ choice or
2. `recreate_tg_mask=yes` runs the `tg_findzo` script.  This is non-optional if the data precede Repro-5 and `asol_update=yes` since the physical coordinates have change. [Though as I write this, this could be relaxed by converting x,y -> ra, dec using the archive L2 file and then back to x,y in the new _repro_evt1 file.]

So we could replace the boolean `recreate_tg_mask`  parameter with a string, just a suggestion: `tg_zo_coordinates`, that would have to be
- `"archive"` to use the L2 REGION coordinates
- `"detect"` to run `tg_findzo`
- a set of ra,dec coordinates that would be converted to x,y using the _repro_evt1 file to feed into `tg_create_mask`

I personally prefer something that could be enumerated in the parameter file itself -- not only do we get the validation "for free" , but we also get the shortcuts like only having to specify the min. unique value that matches one of the enumerations.  So we could call the parameter `tg_zo_method=archive|detect|coordinates` and then a separate `tg_zo_coordinates` that's only used when `tg_zo_method=coordinates`.  But I'm not a big fan of having parameters linked like this (only valid|used if some other parameter is set to some value), but it's not without precedent (eg the scripts' `parameter=yes|no` coupled with `nproc={value}`)

One wrinkle here though is that `chandra_repro` can process multiple datasets, so if you use the coordinates option, those coordinates would be used for all the grating observations in the input stack.  That's probably OK -- just wanted to point it out.

Thoughts?

**Comment by kglotfelty** [comment]
This is closed by #595
