### ISSUE TITLE
add option to chandra_repro to keep all columns

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#5]
Currently chandra_repro omits various columns when going from the L1 to the L2 file which matches what is done in standard data processing/the archive.

We have a request from the HRC team to retain the columns in the L2 file.

I think the best option will be to add a hidden parameter, default is the current behavior, which allow those who need too,  to retain all the columns.

**Comment by DougBurke** [comment]
Are you thinking of following the acis_process_events approach with the eventdef parameter (i.e. give the full list of columns to include [*]) which gives the most flexibility, or a boolean flag which determines whether to do the filter or not? I'm guessing the latter.

[*] I'm not suggesting we copy the eventdef format, since we don't want to specify the datatype here, more that we would have a comma-separated list of columns.

**Comment by kglotfelty** [comment]
Just the later (boolean).

**Comment by kglotfelty** [comment]
This is now #146 .

ACIS already retains all cols -- hrc will with #146.
