### ISSUE TITLE
support csc 2.1 in csc scripts

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#632]
We have a request to support csc 2.1 in the csc scripts. Unfortunately it's not as easy as just changing `csc2.0` to `csc2.1` in a few places because

- we are using a transitional/temporary TAP service/... to access the data
- we don't have image support yet (I think)

Do we want to have a `csc21-not-quite-ready-yet` tag, rather than `csc21`, so that when the 2.1 release happens we can update the script cleanly and also make it obvious to the user that the 2.1 data hasn't finished yet. If we don't, my concern once 2.1 is released, is that people who haven't updated their script release could either get confusing data, or wrong data, or both.

**Comment by kglotfelty** [comment]
I don't know how different the TAP interface is compared to the current csccli/getProperties  interface so that could be major can-of-worms (and whether the TAP interface returns the same .tsv format, or only VOTables -- that's pretty much a non-starter IMO).

By 'images' does that also mean all data products?  The other big thing is if there are new/dropped data products and/or any data products get produced at different cadence (per obsid, per stack, per master source).  That mapping is very messy.  Similarly if any of the standard queries have changed.

Of course ideally the .tsv file would have sufficient meta-data to indicate which version it maps to.... presumably the data products will :stuck_out_tongue_winking_eye:
