### ISSUE TITLE
replace h/c 2.7 in python hack

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#86]
There are a couple places where I've got this hack

https://github.com/cxcsds/ciao-contrib/blob/291112c2c8f37f9f08e0f891a2a903cbf2632e08/ciao-4.9/contrib/bin/tgmask2reg#L29

which needs to adopt @DougBurke 's scheme to get the python major/minor version numbers instead of hard coding 2.7.

**Comment by DougBurke** [comment]
This should be fixed in #100 - although the presence of this code is actually an affront to proper engineering practices and should be burnt with fire (I am the person who wrote the original code I am now criticizing) and should probably be removed once we come up with a standardized install/test set up.
